### ISSUE TITLE
Attempt to instantiate abstract class in CglCliqueHelper.cpp

### ISSUE THREAD

**Issue by svigerske** [coin-or/Cgl#1]
Issue created by migration from Trac.

Original creator: dan.gordon

Original creation time: 2006-06-22 01:19:36

Assignee: somebody

Version: 

When I try to compile in CglClique under Mac OSX 10.4, I get the following error:
```
CglCliqueHelper.cpp:86: error: cannot allocate an object of abstract type 'const CoinPackedVectorBase'
/devel/COIN/Coin-CoinAll/CoinUtils/src/CoinPackedVectorBase.hpp:25: note:   because the following virtual functions are pure within 'const CoinPackedVectorBase':
/devel/COIN/Coin-CoinAll/CoinUtils/src/CoinPackedVectorBase.hpp:31: note:  virtual int CoinPackedVectorBase::getNumElements() const
...
```

This is obviously because `CoinPackedVectorBase::GetVector(...)` returns by value. Hence the error is fixed by changing lines like

`const CoinPackedVectorBase& vec = mcol.getVector(sp_orig_col_ind[j]);`

to

`const CoinShallowPackedVector vec = mcol.getVector(sp_orig_col_ind[j]);`

**Comment by svigerske** [comment]
Comment by fmargot created at 2006-06-22 12:42:53

Changing assignee from somebody to fmargot.

**Comment by svigerske** [comment]
Comment by fmargot created at 2006-06-22 12:43:06

Resolution: fixed
